uploaded
vendorsfullcalendarcorelocaleskoJsContent
	^ '(function (global, factory) {
    typeof exports === ''object'' && typeof module !== ''undefined'' ? module.exports = factory() :
    typeof define === ''function'' && define.amd ? define(factory) :
    (global = global || self, (global.FullCalendarLocales = global.FullCalendarLocales || {}, global.FullCalendarLocales.ko = factory()));
}(this, function () { ''use strict'';

    var ko = {
        code: "ko",
        buttonText: {
            prev: "ì´ì ë¬",
            next: "ë¤ìë¬",
            today: "ì¤ë",
            month: "ì",
            week: "ì£¼",
            day: "ì¼",
            list: "ì¼ì ëª©ë¡"
        },
        weekLabel: "ì£¼",
        allDayText: "ì¢ì¼",
        eventLimitText: "ê°",
        noEventsMessage: "ì¼ì ì´ ììµëë¤"
    };

    return ko;

}));
'