uploaded
vendorsselect2jsi18nzhTWJsContent
	^ '/*! Select2 4.0.6-rc.1 | https://github.com/select2/select2/blob/master/LICENSE.md */

(function(){if(jQuery&&jQuery.fn&&jQuery.fn.select2&&jQuery.fn.select2.amd)var e=jQuery.fn.select2.amd;return e.define("select2/i18n/zh-TW",[],function(){return{inputTooLong:function(e){var t=e.input.length-e.maximum,n="è«åªæ"+t+"åå­å";return n},inputTooShort:function(e){var t=e.minimum-e.input.length,n="è«åè¼¸å¥"+t+"åå­å";return n},loadingMore:function(){return"è¼å¥ä¸­â¦"},maximumSelected:function(e){var t="ä½ åªè½é¸ææå¤"+e.maximum+"é ";return t},noResults:function(){return"æ²ææ¾å°ç¸ç¬¦çé ç®"},searching:function(){return"æå°ä¸­â¦"}}}),{define:e.define,require:e.require}})();'