uploaded
vendorsfullcalendarcorelocaleszhtwJsContent
	^ '(function (global, factory) {
    typeof exports === ''object'' && typeof module !== ''undefined'' ? module.exports = factory() :
    typeof define === ''function'' && define.amd ? define(factory) :
    (global = global || self, (global.FullCalendarLocales = global.FullCalendarLocales || {}, global.FullCalendarLocales[''zh-tw''] = factory()));
}(this, function () { ''use strict'';

    var zhTw = {
        code: "zh-tw",
        buttonText: {
            prev: "ä¸æ",
            next: "ä¸æ",
            today: "ä»å¤©",
            month: "æ",
            week: "é±",
            day: "å¤©",
            list: "æ´»ååè¡¨"
        },
        weekLabel: "å¨",
        allDayText: "æ´å¤©",
        eventLimitText: ''é¡¯ç¤ºæ´å¤'',
        noEventsMessage: "æ²¡æä»»ä½æ´»å"
    };

    return zhTw;

}));
'