uploaded
vendorsfullcalendarcorelocalesthJsContent
	^ '(function (global, factory) {
    typeof exports === ''object'' && typeof module !== ''undefined'' ? module.exports = factory() :
    typeof define === ''function'' && define.amd ? define(factory) :
    (global = global || self, (global.FullCalendarLocales = global.FullCalendarLocales || {}, global.FullCalendarLocales.th = factory()));
}(this, function () { ''use strict'';

    var th = {
        code: "th",
        buttonText: {
            prev: "à¸¢à¹à¸­à¸",
            next: "à¸à¸±à¸à¹à¸",
            today: "à¸§à¸±à¸à¸à¸µà¹",
            month: "à¹à¸à¸·à¸­à¸",
            week: "à¸ªà¸±à¸à¸à¸²à¸«à¹",
            day: "à¸§à¸±à¸",
            list: "à¹à¸à¸à¸à¸²à¸"
        },
        allDayText: "à¸à¸¥à¸­à¸à¸§à¸±à¸",
        eventLimitText: "à¹à¸à¸´à¹à¸¡à¹à¸à¸´à¸¡",
        noEventsMessage: "à¹à¸¡à¹à¸¡à¸µà¸à¸´à¸à¸à¸£à¸£à¸¡à¸à¸µà¹à¸à¸°à¹à¸ªà¸à¸"
    };

    return th;

}));
'