rendering-javascript
renderJavascriptResourcesOn: canvas
  canvas script url: SAFileLibrary / #'vendorsjqueryjqueryminJs'.
  canvas script url: SAFileLibrary / #'vendorspopperjspopperJs'.
  canvas script url: SAFileLibrary / #'vendorsbootstrapjsbootstrapminJs'.
  canvas script
    url: SAFileLibrary / #'vendorsoverlayscrollbarsjqueryoverlayScrollbarsminJs'.
  canvas script url: SAFileLibrary / #'vendorsflotjqueryflotJs'.
  canvas script url: SAFileLibrary / #'vendorsflotjqueryflotresizeJs'.
  canvas script url: SAFileLibrary / #'vendorsflotflotcurvedlinescurvedLinesJs'.
  canvas script url: SAFileLibrary / #'vendorspeityjquerypeityminJs'.
  canvas script url: SAFileLibrary / #'vendorsjqvmapjqueryvmapminJs'.
  canvas script
    url: SAFileLibrary / #'vendorsjqvmapmapscontinentsjqueryvmapaustraliaJs'.
  canvas script
    url: SAFileLibrary / #'vendorsjqueryeasypiechartjqueryeasypiechartminJs'.
  canvas script url: SAFileLibrary / #'vendorsfullcalendarcoremainminJs'.
  canvas script url: SAFileLibrary / #'vendorsfullcalendardaygridmainminJs'.
  canvas script url: SAFileLibrary / #'jsappminJs'